### ISSUE TITLE
XiaomiGwDevice._push_data({'availability': False})

### ISSUE THREAD

**Issue by darksider4all** [cadavre/miio_gateway#3] opened 2019-09-02 05:30 UTC
My last night logs, and this happens once a day at least, and beaks my whole system down, needing a restart 

2019-09-02 06:19:27 ERROR (MainThread) [homeassistant.core] Error doing job: Exception in callback XiaomiGwDevice._push_data({'availability': False})
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
TypeError: _push_data() missing 3 required positional arguments: 'sid', 'event', and 'params'
2019-09-02 06:19:27 ERROR (MainThread) [homeassistant.core] Error doing job: Exception in callback XiaomiGwDevice._push_data({'availability': False})
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
TypeError: _push_data() missing 3 required positional arguments: 'sid', 'event', and 'params'
2019-09-02 06:19:27 ERROR (MainThread) [homeassistant.core] Error doing job: Exception in callback XiaomiGwDevice._push_data({'availability': False})
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
TypeError: _push_data() missing 3 required positional arguments: 'sid', 'event', and 'params'
2019-09-02 06:19:27 ERROR (MainThread) [homeassistant.core] Error doing job: Exception in callback XiaomiGwDevice._push_data({'availability': False})
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
TypeError: _push_data() missing 3 required positional arguments: 'sid', 'event', and 'params'
2019-09-02 06:19:27 ERROR (MainThread) [homeassistant.core] Error doing job: Exception in callback XiaomiGwDevice._push_data({'availability': False})
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
TypeError: _push_data() missing 3 required positional arguments: 'sid', 'event', and 'params'
2019-09-02 06:19:27 ERROR (MainThread) [homeassistant.core] Error doing job: Exception in callback XiaomiGwDevice._push_data({'availability': False})
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
TypeError: _push_data() missing 3 required positional arguments: 'sid', 'event', and 'params'
2019-09-02 06:19:27 ERROR (MainThread) [homeassistant.core] Error doing job: Exception in callback XiaomiGwDevice._push_data({'availability': False})
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
TypeError: _push_data() missing 3 required positional arguments: 'sid', 'event', and 'params'
2019-09-02 06:19:27 ERROR (MainThread) [homeassistant.core] Error doing job: Exception in callback XiaomiGwDevice._push_data({'availability': False})
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
TypeError: _push_data() missing 3 required positional arguments: 'sid', 'event', and 'params'
2019-09-02 06:20:28 INFO (MainThread) [homeassistant.components.flux.switch] Lights updated to mired:526 brightness:None, 100% of night cycle complete at 2019-09-02 06:20:28.002274+03:00
2019-09-02 06:21:29 INFO (MainThread) [homeassistant.components.flux.switch] Lights updated to mired:526 brightness:None, 100% of night cycle complete at 2019-09-02 06:21:29.003373+03:00
2019-09-02 06:22:30 INFO (MainThread) [homeassistant.components.flux.switch] Lights updated to mired:526 brightness:None, 100% of night cycle complete at 2019-09-02 06:22:30.003068+03:00
2019-09-02 06:23:31 INFO (MainThread) [homeassistant.components.flux.switch] Lights updated to mired:526 brightness:None, 100% of night cycle complete at 2019-09-02 06:23:31.002683+03:00
2019-09-02 06:23:58 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.dark_home_temperature is taking over 10 seconds
2019-09-02 06:24:32 INFO (MainThread) [homeassistant.components.flux.switch] Lights updated to mired:526 brightness:None, 100% of night cycle complete at 2019-09-02 06:24:32.003875+03:00
2019-09-02 06:25:33 INFO (MainThread) [homeassistant.components.flux.switch] Lights updated to mired:526 brightness:None, 100% of night cycle complete at 2019-09-02 06:25:33.003587+03:00
2019-09-02 06:26:34 INFO (MainThread) [homeassistant.components.flux.switch] Lights updated to mired:526 brightness:None, 100% of night cycle complete at 2019-09-02 06:26:34.002012+03:00
2019-09-02 06:27:35 INFO (MainThread) [homeassistant.components.flux.switch] Lights updated to mired:526 brightness:None, 100% of night cycle complete at 2019-09-02 06:27:35.003236+03:00
2019-09-02 06:28:36 INFO (MainThread) [homeassistant.components.flux.switch] Lights updated to mired:526 brightness:None, 100% of night cycle complete at 2019-09-02 06:28:36.003071+03:00
2019-09-02 06:29:37 INFO (MainThread) [homeassistant.components.flux.switch] Lights updated to mired:526 brightness:None, 100% of night cycle complete at 2019-09-02 06:29:37.002168+03:00
2019-09-02 06:30:28 INFO (MainThread) [custom_components.miio_gateway] Gateway became unavailable by timeout!
2019-09-02 06:30:28 ERROR (MainThread) [homeassistant.core] Error doing job: Exception in callback XiaomiGwDevice._push_data({'availability': False})

**Comment by cadavre** [comment] 2019-09-17 08:00
Duplicate of #2

**Closed by cadavre** 2019-09-17 08:00 UTC
